#!/usr/bin/env python3
"""Verify docs/example/ is a byte-identical mirror of example/ (except runtime artifacts)."""

import filecmp
import sys
from pathlib import Path

IGNORE = {
    "__pycache__",
    "logs",
    "outputs",
    "outputs_multilabel",
    "benchmark_results",  # gitignored runtime output of the benchmark example
    ".ipynb_checkpoints",
    ".gitignore",
    ".scratch",
}
# .gz/.log: runtime artifacts at any depth on either side of the mirror.
IGNORE_SUFFIXES = (".gz", ".log")
# .pdf: gitignored example/notebooks/*/*.pdf plots (never tracked, so no
# mirror drift can be masked). Exempt ONLY at that depth — a .pdf directly
# under example/notebooks/<dir>/, exactly the .gitignore pattern — so a PDF
# appearing anywhere else still participates in the sync check.
PDF_EXEMPT_SUFFIX = ".pdf"
PDF_EXEMPT_DIR = "notebooks"
# Files that exist ONLY in docs/example/ by design: the .md tutorial wrappers
# generated by scripts/generate_md_from_notebook.py / generate_md_from_marimo.py.
# Consulted in the right_only loop ONLY — a .md mirrored on BOTH sides (e.g.
# notebooks/overview.md) must still match byte-for-byte via diff_files/left_only.
DOCS_ONLY_SUFFIXES = (".md",)

EXAMPLE_DIR = Path("example")
DOCS_EXAMPLE_DIR = Path("docs/example")


def _should_ignore(name: str, path: str = "") -> bool:
    if name in IGNORE:
        return True
    if any(name.endswith(suffix) for suffix in IGNORE_SUFFIXES):
        return True
    # The .pdf exemption is path-shaped, not depth-free: only a PDF directly
    # under notebooks/<one-dir>/ (the .gitignore pattern above) is skipped,
    # on both sides of the mirror like the suffix exemptions.
    if name.endswith(PDF_EXEMPT_SUFFIX):
        parts = path.split("/") if path else []
        return len(parts) == 2 and parts[0] == PDF_EXEMPT_DIR
    return False


def _is_docs_only(name: str) -> bool:
    return any(name.endswith(suffix) for suffix in DOCS_ONLY_SUFFIXES)


def check_sync(dcmp: filecmp.dircmp, path: str = "") -> list[str]:
    """Recursively check for differences between two directory trees."""
    errors = []

    for name in dcmp.left_only:
        if not _should_ignore(name, path):
            errors.append(
                f"ONLY in example/: {path}/{name}" if path else f"ONLY in example/: {name}"
            )

    for name in dcmp.right_only:
        # Docs-only wrapper files are intentional; never applies to left_only/diff_files.
        if not _should_ignore(name, path) and not _is_docs_only(name):
            errors.append(
                f"ONLY in docs/example/: {path}/{name}"
                if path
                else f"ONLY in docs/example/: {name}"
            )

    # Byte-level comparison: dircmp's diff_files uses shallow (stat-signature)
    # matching, which reports "equal" whenever mode+size+mtime coincide without
    # reading the bytes — a same-size content divergence whose mtimes match
    # would slip through. cmpfiles(..., shallow=False) always reads the bytes.
    # (dircmp's own `shallow=` kwarg is Python 3.13+ only; this repo supports
    # 3.10+, so re-compare common_files here instead.)
    _, mismatch, unreadable = filecmp.cmpfiles(
        dcmp.left, dcmp.right, dcmp.common_files, shallow=False
    )
    for name in mismatch:
        errors.append(f"DIFFER: {path}/{name}" if path else f"DIFFER: {name}")
    for name in unreadable:
        errors.append(f"UNREADABLE: {path}/{name}" if path else f"UNREADABLE: {name}")

    for subdir, sub_dcmp in dcmp.subdirs.items():
        sub_path = f"{path}/{subdir}" if path else subdir
        errors.extend(check_sync(sub_dcmp, sub_path))

    return errors


def main() -> int:
    if not EXAMPLE_DIR.exists():
        print(f"ERROR: {EXAMPLE_DIR} does not exist")
        return 1
    if not DOCS_EXAMPLE_DIR.exists():
        print(f"ERROR: {DOCS_EXAMPLE_DIR} does not exist")
        return 1

    dcmp = filecmp.dircmp(str(EXAMPLE_DIR), str(DOCS_EXAMPLE_DIR), ignore=list(IGNORE))
    errors = check_sync(dcmp)

    if errors:
        print("SYNC ERRORS:")
        for err in errors:
            print(f"  {err}")
        return 1

    print("OK: docs/example/ is in sync with example/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
