benchmark:
  name: "My First Benchmark"
  description: "Comparing DNA models on promoter prediction"

  models:
    - name: "Plant DNABERT"
      path: "zhangtaolab/plant-dnabert-BPE"
      source: "huggingface"

    - name: "Plant DNAGPT"
      path: "zhangtaolab/plant-dnagpt-BPE"
      source: "huggingface"

  datasets:
    - name: "promoter_data"
      path: "path/to/your/data.csv"
      text_column: "sequence"
      label_column: "label"
      task_type: "binary"
      num_labels: 2
      label_names:
        - "negative"
        - "postive"
      threshold: 0.5

  metrics:
    - "accuracy"
    - "f1_score"
    - "precision"
    - "recall"

  plot:
    format: "pdf"


inference:
    batch_size: 16
    max_length: 512
    device: "auto"
    num_workers: 4
    use_fp16: False
    output_dir: "benchmark_results"